create table noteful_notes (
  id integer primary key generated by default as identity,
  note_name text not null,
  modified timestamptz not null default now(),
  content text not null,
  folder_id integer references noteful_folders(id)
  on delete cascade not null
);